/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Flashcard = IDL.Record({
  'id' : IDL.Nat,
  'term' : IDL.Text,
  'usage' : IDL.Text,
  'category' : IDL.Text,
  'definition' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'text' : IDL.Text,
  'category' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Scenario = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'correctIndex' : IDL.Int,
  'explanation' : IDL.Text,
  'category' : IDL.Text,
  'choices' : IDL.Vec(IDL.Text),
  'situation' : IDL.Text,
});
export const VideoLesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'learningObjectives' : IDL.Vec(IDL.Text),
  'summary' : IDL.Text,
  'youtubeId' : IDL.Text,
  'quizQuestions' : IDL.Vec(Question),
});
export const LessonWithQuestions = IDL.Record({
  'lesson' : VideoLesson,
  'questions' : IDL.Vec(Question),
});

export const idlService = IDL.Service({
  'countAllData' : IDL.Func([], [IDL.Nat], ['query']),
  'countFlashcardsByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'countQuestionsByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'explainAnswer' : IDL.Func([IDL.Nat, IDL.Int], [IDL.Text], ['query']),
  'explainScenario' : IDL.Func([IDL.Nat, IDL.Int], [IDL.Text], ['query']),
  'getAllFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
  'getAllVideoLessons' : IDL.Func([], [IDL.Vec(VideoLesson)], ['query']),
  'getFlashcardsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Flashcard)],
      ['query'],
    ),
  'getQuestionsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getVideoLessonsWithQuestions' : IDL.Func(
      [],
      [IDL.Vec(LessonWithQuestions)],
      ['query'],
    ),
  'initializeData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Flashcard = IDL.Record({
    'id' : IDL.Nat,
    'term' : IDL.Text,
    'usage' : IDL.Text,
    'category' : IDL.Text,
    'definition' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'text' : IDL.Text,
    'category' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Scenario = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'correctIndex' : IDL.Int,
    'explanation' : IDL.Text,
    'category' : IDL.Text,
    'choices' : IDL.Vec(IDL.Text),
    'situation' : IDL.Text,
  });
  const VideoLesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'learningObjectives' : IDL.Vec(IDL.Text),
    'summary' : IDL.Text,
    'youtubeId' : IDL.Text,
    'quizQuestions' : IDL.Vec(Question),
  });
  const LessonWithQuestions = IDL.Record({
    'lesson' : VideoLesson,
    'questions' : IDL.Vec(Question),
  });
  
  return IDL.Service({
    'countAllData' : IDL.Func([], [IDL.Nat], ['query']),
    'countFlashcardsByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'countQuestionsByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'explainAnswer' : IDL.Func([IDL.Nat, IDL.Int], [IDL.Text], ['query']),
    'explainScenario' : IDL.Func([IDL.Nat, IDL.Int], [IDL.Text], ['query']),
    'getAllFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
    'getAllVideoLessons' : IDL.Func([], [IDL.Vec(VideoLesson)], ['query']),
    'getFlashcardsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Flashcard)],
        ['query'],
      ),
    'getQuestionsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getVideoLessonsWithQuestions' : IDL.Func(
        [],
        [IDL.Vec(LessonWithQuestions)],
        ['query'],
      ),
    'initializeData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };