/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Flashcard {
  'id' : bigint,
  'term' : string,
  'usage' : string,
  'category' : string,
  'definition' : string,
}
export interface LessonWithQuestions {
  'lesson' : VideoLesson,
  'questions' : Array<Question>,
}
export interface Question {
  'id' : bigint,
  'correctIndex' : bigint,
  'explanation' : string,
  'text' : string,
  'category' : string,
  'options' : Array<string>,
}
export interface Scenario {
  'id' : bigint,
  'question' : string,
  'correctIndex' : bigint,
  'explanation' : string,
  'category' : string,
  'choices' : Array<string>,
  'situation' : string,
}
export interface VideoLesson {
  'id' : bigint,
  'title' : string,
  'learningObjectives' : Array<string>,
  'summary' : string,
  'youtubeId' : string,
  'quizQuestions' : Array<Question>,
}
export interface _SERVICE {
  'countAllData' : ActorMethod<[], bigint>,
  'countFlashcardsByCategory' : ActorMethod<[], Array<[string, bigint]>>,
  'countQuestionsByCategory' : ActorMethod<[], Array<[string, bigint]>>,
  'explainAnswer' : ActorMethod<[bigint, bigint], string>,
  'explainScenario' : ActorMethod<[bigint, bigint], string>,
  'getAllFlashcards' : ActorMethod<[], Array<Flashcard>>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getAllScenarios' : ActorMethod<[], Array<Scenario>>,
  'getAllVideoLessons' : ActorMethod<[], Array<VideoLesson>>,
  'getFlashcardsByCategory' : ActorMethod<[string], Array<Flashcard>>,
  'getQuestionsByCategory' : ActorMethod<[string], Array<Question>>,
  'getVideoLessonsWithQuestions' : ActorMethod<[], Array<LessonWithQuestions>>,
  'initializeData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];