/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LessonWithQuestions {
    lesson: VideoLesson;
    questions: Array<Question>;
}
export interface Question {
    id: bigint;
    correctIndex: bigint;
    explanation: string;
    text: string;
    category: string;
    options: Array<string>;
}
export interface VideoLesson {
    id: bigint;
    title: string;
    learningObjectives: Array<string>;
    summary: string;
    youtubeId: string;
    quizQuestions: Array<Question>;
}
export interface Flashcard {
    id: bigint;
    term: string;
    usage: string;
    category: string;
    definition: string;
}
export interface Scenario {
    id: bigint;
    question: string;
    correctIndex: bigint;
    explanation: string;
    category: string;
    choices: Array<string>;
    situation: string;
}
export interface backendInterface {
    countAllData(): Promise<bigint>;
    countFlashcardsByCategory(): Promise<Array<[string, bigint]>>;
    countQuestionsByCategory(): Promise<Array<[string, bigint]>>;
    explainAnswer(questionId: bigint, chosenIndex: bigint): Promise<string>;
    explainScenario(scenarioId: bigint, chosenIndex: bigint): Promise<string>;
    getAllFlashcards(): Promise<Array<Flashcard>>;
    getAllQuestions(): Promise<Array<Question>>;
    getAllScenarios(): Promise<Array<Scenario>>;
    getAllVideoLessons(): Promise<Array<VideoLesson>>;
    getFlashcardsByCategory(cat: string): Promise<Array<Flashcard>>;
    getQuestionsByCategory(cat: string): Promise<Array<Question>>;
    getVideoLessonsWithQuestions(): Promise<Array<LessonWithQuestions>>;
    initializeData(): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async countAllData(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.countAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countAllData();
            return result;
        }
    }
    async countFlashcardsByCategory(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.countFlashcardsByCategory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countFlashcardsByCategory();
            return result;
        }
    }
    async countQuestionsByCategory(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.countQuestionsByCategory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countQuestionsByCategory();
            return result;
        }
    }
    async explainAnswer(arg0: bigint, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.explainAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.explainAnswer(arg0, arg1);
            return result;
        }
    }
    async explainScenario(arg0: bigint, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.explainScenario(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.explainScenario(arg0, arg1);
            return result;
        }
    }
    async getAllFlashcards(): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFlashcards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFlashcards();
            return result;
        }
    }
    async getAllQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return result;
        }
    }
    async getAllScenarios(): Promise<Array<Scenario>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllScenarios();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllScenarios();
            return result;
        }
    }
    async getAllVideoLessons(): Promise<Array<VideoLesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideoLessons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideoLessons();
            return result;
        }
    }
    async getFlashcardsByCategory(arg0: string): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlashcardsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlashcardsByCategory(arg0);
            return result;
        }
    }
    async getQuestionsByCategory(arg0: string): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByCategory(arg0);
            return result;
        }
    }
    async getVideoLessonsWithQuestions(): Promise<Array<LessonWithQuestions>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoLessonsWithQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoLessonsWithQuestions();
            return result;
        }
    }
    async initializeData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeData();
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
